### ISSUE TITLE
problem with password

### ISSUE THREAD

**Issue by gabriel-alex** [linto-ai/linto-os-generator#1]
Hello, 

First, in order to create the OS image, I had to modified the 'generator.sh' file.
I don't know if it specific to my computer or not. 
  mount /dev/mapper/loop${LOOP_ID}p2 ${MNT} --> mount /dev/mapper/loop4${LOOP_ID}p2 ${MNT}
  mount /dev/mapper/loop${LOOP_ID}p1 ${BOOT} --> mount /dev/mapper/loop4${LOOP_ID}p1 ${BOOT}
I added '4' after 'loop'.

Second, I have some issue to connect to the raspberry hosting Linto through ssh, password is wrong. When I try to be super user, I have the same problem. Are credentials correct? is it really pi as password?

Third, Linto is open source but what is the exact licence ?

Kind regards.

**Comment by damienlaine** [comment]
Greetings,

I can confirm that the generator script might need some tweaks to run on your computer. Out of the box it works well on a basic fresh install Debian Box. Inner functionalities scripted here are explicit enough to get customized for a specific need (Ubuntu...)

According to the repo's Readme, the password "pi" is the one used on the provided ready-to-boot image (eventhough, the link is still missing for downloading it)

Password of your choice is set in the final step of the image generation process.
You can also change it at any moment while the image is mounted as a loopback device... (Enter Chroot). I bet you took a basic Raspian lite image from Raspberry's as a source... therefore the standard password shall be "raspbian"

Finaly, every LinTO's bit is distributed under Gnu Affero AGPLV3.

**Comment by damienlaine** [comment]
Closed
